src/main/java/br/apolo/data/model/UserGroup.java
package br.apolo.data.model;

import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.CascadeType;
import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.annotations.Type;

import br.apolo.common.util.InputLength;
import br.apolo.data.entitylistener.AuditLogListener;
import br.apolo.data.enums.UserPermission;

@Entity
@EntityListeners(value = AuditLogListener.class)
@Table(name = "user_group")
@AttributeOverride(name = "id", column = @Column(name = "user_group_id"))
public class UserGroup extends AuditableBaseEntity {

	private static final long serialVersionUID = -7985007135932159381L;
	
	@Column(name = "name", length = InputLength.MEDIUM, nullable = false)
	@NotNull
	@Size(min = 1, max = InputLength.MEDIUM)
	private String name;

	@ElementCollection(targetClass = UserPermission.class, fetch = FetchType.EAGER)
	@CollectionTable(name = "group_permission", 
			joinColumns = @JoinColumn(name = "group_id", referencedColumnName = "user_group_id", insertable = true, updatable = true, nullable = false), 
			uniqueConstraints = @UniqueConstraint(columnNames = {"group_id", "permission_name" }, name = "uq_group_permission")
	)
	@Type(type = "br.apolo.data.enums.usertype.UserPermissionUserType")
	@Column(name = "permission_name")
	@NotNull
	private Set<UserPermission> permissions;

	@ManyToMany(mappedBy = "groups", cascade = CascadeType.MERGE)
	private Set<User> users;

	public String getName() {
		return name;
	}

	public void setName(String value) {
		name = value;
	}

	public Set<User> getUsers() {
		return users;
	}

	public void setUsers(Set<User> users1) {
		this.users = users1;
	}

	public Set<UserPermission> getPermissions() {
		return permissions;
	}

	public void setPermissions(Set<UserPermission> perms) {
		this.permissions = perms;
	}

}

src/main/java/br/apolo/data/model/interfaces/IAuditableEntity.java
package br.apolo.data.model.interfaces;

import java.util.Date;

import br.apolo.data.model.User;

public interface IAuditableEntity {

	public Date getCreationDate();

	public void setCreationDate(Date newCreationDate);

	public User getCreatedBy();

	public void setCreatedBy(User newCreatedBy);

	public Date getLastUpdateDate();

	public void setLastUpdateDate(Date newLastUpdateDate);

	public User getLastUpdatedBy();

	public void setLastUpdatedBy(User newLastUpdatedBy);
}

src/main/java/br/apolo/web/controller/UserGroupController.java
package br.apolo.web.controller;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import net.sf.json.JSONObject;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.support.DefaultMessageSourceResolvable;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.validation.ObjectError;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;

import br.apolo.business.service.UserGroupService;
import br.apolo.common.exception.AccessDeniedException;
import br.apolo.common.util.MessageBundle;
import br.apolo.data.enums.UserPermission;
import br.apolo.data.model.UserGroup;
import br.apolo.security.SecuredEnum;
import br.apolo.web.enums.Navigation;

@Controller
@RequestMapping(value = "/user-group")
public class UserGroupController extends BaseController<UserGroup> {

	@Autowired
	private UserGroupService userGroupService;
	
	@SecuredEnum({ UserPermission.USER_PERMISSION_CREATE, UserPermission.USER_PERMISSION_EDIT })
	@RequestMapping(value = "save", method = RequestMethod.POST)
	public ModelAndView save(@Valid @ModelAttribute("entity") UserGroup entity, BindingResult result, HttpServletRequest request) {
		ModelAndView mav = new ModelAndView();
		
		/*
		 * Object validation
		 */
		if (result.hasErrors() || entityHasErrors(entity)) {
			mav.setViewName(getRedirectionPath(request, Navigation.USER_PERMISSION_NEW, Navigation.USER_PERMISSION_EDIT));
			
			mav.addObject("userGroup", entity);
			mav.addObject("permissionList", userGroupService.getUserPermissionList());
			mav.addObject("readOnly", false);
			mav.addObject("error", true);
			
			StringBuilder message = new StringBuilder();
			for (ObjectError error : result.getAllErrors()) {
				DefaultMessageSourceResolvable argument = (DefaultMessageSourceResolvable) error.getArguments()[0];
				
				message.append(MessageBundle.getMessageBundle("common.field") + " " + MessageBundle.getMessageBundle("user.group." + argument.getDefaultMessage()) + ": " + error.getDefaultMessage() + "\n <br />");
			}
			
			message.append(additionalValidation(entity));
			
			mav.addObject("message", message.toString());
			
			return mav;
		} 
		
		if (entity != null) {
			try {
				userGroupService.save(entity);
				
				mav = view(entity.getId(), request);
				mav.addObject("msg", true);
				mav.addObject("message", MessageBundle.getMessageBundle("common.msg.save.success"));
			} catch (AccessDeniedException e) {
				mav = list(request);
				mav.addObject("error", true);
				mav.addObject("message", e.getCustomMsg());
			}
		}
		
		return mav;
	}

	@SecuredEnum(UserPermission.USER_PERMISSION_LIST)
	@RequestMapping(value = "list", method = RequestMethod.GET)
	public ModelAndView list(HttpServletRequest request) {
		return list(1, request);
	}
	
	@SecuredEnum(UserPermission.USER_PERMISSION_LIST)
	@RequestMapping(value = "list/{pageNumber}", method = RequestMethod.GET)
	public ModelAndView list(@PathVariable Integer pageNumber, HttpServletRequest request) {
		breadCrumbService.addNode(MessageBundle.getMessageBundle("breadcrumb.usergroup.list"), 1, request);
		
		ModelAndView mav = new ModelAndView(Navigation.USER_PERMISSION_LIST.getPath());
		
		Page<UserGroup> page = userGroupService.list(pageNumber);
		
	    configurePageable(mav, page, "/user-group/list");
	    
	    mav.addObject("searchParameter", "");
		
		if (page != null && page.getContent() != null) {
			mav.addObject("userGroupList", page.getContent());	
		}
		
		return mav;
	}

	@SecuredEnum(UserPermission.USER_PERMISSION_CREATE)
	@RequestMapping(value = "new", method = RequestMethod.GET)
	public ModelAndView create(HttpServletRequest request) {
		breadCrumbService.addNode(MessageBundle.getMessageBundle("breadcrumb.usergroup.new"), 1, request);
		
		ModelAndView mav = new ModelAndView(Navigation.USER_PERMISSION_NEW.getPath());
		
		UserGroup userGroup = new UserGroup();
		
		userGroup.setCreatedBy(userGroupService.getAuthenticatedUser());
		userGroup.setCreationDate(new Date());
		
		userGroup.setLastUpdatedBy(userGroupService.getAuthenticatedUser());
		userGroup.setLastUpdateDate(new Date());
		
		mav.addObject("userGroup", userGroup);
		mav.addObject("permissionList", userGroupService.getUserPermissionList());
		mav.addObject("readOnly", false);
		
		return mav;
	}
	
	@SecuredEnum(UserPermission.USER_PERMISSION_EDIT)
	@RequestMapping(value = "edit/{id}", method = RequestMethod.GET)
	public ModelAndView edit(@PathVariable Long id, HttpServletRequest request) {
		breadCrumbService.addNode(MessageBundle.getMessageBundle("breadcrumb.usergroup.edit"), 2, request);
		
		ModelAndView mav = new ModelAndView(Navigation.USER_PERMISSION_EDIT.getPath());
		
		UserGroup userGroup = userGroupService.find(id);
		
		userGroup.setLastUpdatedBy(userGroupService.getAuthenticatedUser());
		userGroup.setLastUpdateDate(new Date());
		
		mav.addObject("userGroup", userGroup);
		mav.addObject("permissionList", userGroupService.getUserPermissionList());
		mav.addObject("readOnly", false);
		
		return mav;
	}
	
	@Override
	@SecuredEnum(UserPermission.USER_PERMISSION_REMOVE)
	@RequestMapping(value = "remove/{id}", method = RequestMethod.GET)
	public @ResponseBody String remove(@PathVariable Long id) {
		String result = "";
		
		JSONObject jsonSubject = new JSONObject();
		JSONObject jsonItem = new JSONObject();
		
		UserGroup userGroup = userGroupService.find(id);
		
		if (userGroup != null) {
			if (userGroup.getUsers() != null && !userGroup.getUsers().isEmpty()) {
				result = MessageBundle.getMessageBundle("user.group.msg.error.has.associated.users");
				jsonItem.put("success", false);
			} else {
				try {
					userGroupService.remove(userGroup);
					
					result = MessageBundle.getMessageBundle("common.msg.remove.success");
					jsonItem.put("success", true);
				} catch (Throwable e) {
					result = MessageBundle.getMessageBundle("common.remove.msg.error");
					jsonItem.put("success", false);
				}
			}
		}
		
		jsonItem.put("message", result);
		jsonSubject.accumulate("result", jsonItem);
		
		return jsonSubject.toString();
	}
	
	@SecuredEnum(UserPermission.USER_PERMISSION_REMOVE)
	@RequestMapping(value = "remove-registry/{id}", method = RequestMethod.GET)
	public ModelAndView removeRegistry(@PathVariable Long id, HttpServletRequest request) {
		ModelAndView mav = new ModelAndView(Navigation.USER_PERMISSION_LIST.getPath());
		
		UserGroup userGroup = userGroupService.find(id);
		
		if (userGroup != null) {
			try {
				userGroupService.remove(userGroup);

				mav = list(request);
				mav.addObject("msg", true);
				mav.addObject("message", MessageBundle.getMessageBundle("common.msg.remove.success"));
			} catch (Throwable e) {
				mav = list(request);
				mav.addObject("error", true);
				mav.addObject("message", MessageBundle.getMessageBundle("common.remove.msg.error"));
			}
		}
		
		return mav;
	}
	
	@SecuredEnum({UserPermission.USER_PERMISSION_VIEW, UserPermission.USER_PERMISSION_LIST, UserPermission.USER_LIST})
	@RequestMapping(value = "view/{id}", method = RequestMethod.GET)
	public ModelAndView view(@PathVariable Long id, HttpServletRequest request) {
		breadCrumbService.addNode(MessageBundle.getMessageBundle("breadcrumb.usergroup"), 2, request);
		
		ModelAndView mav = new ModelAndView(Navigation.USER_PERMISSION_VIEW.getPath());
		
		UserGroup userGroup = userGroupService.find(id);
		
		mav.addObject("userGroup", userGroup);
		mav.addObject("readOnly", true);
		
		return mav;
	}

	@SecuredEnum(UserPermission.USER_PERMISSION_LIST)
	@RequestMapping(value = "search", method = RequestMethod.POST)
	public ModelAndView search(@ModelAttribute("searchParameter") String searchParameter, HttpServletRequest request) {
		return search(1, searchParameter, request);
	}
	
	@SecuredEnum(UserPermission.USER_PERMISSION_LIST)
	@RequestMapping(value = "search/{searchParameter}/{pageNumber}", method = RequestMethod.GET)
	public ModelAndView search(@PathVariable Integer pageNumber, @PathVariable String searchParameter, HttpServletRequest request) {
		breadCrumbService.addNode(MessageBundle.getMessageBundle("breadcrumb.usergroup.list"), 2, request);
		
		ModelAndView mav = new ModelAndView(Navigation.USER_PERMISSION_LIST.getPath());
		
		Page<UserGroup> page = userGroupService.search(pageNumber, searchParameter);
		
		configurePageable(mav, page, "/user-group/search/"+searchParameter);
		
		mav.addObject("searchParameter", searchParameter);
		
		if (page != null && page.getContent() != null) {
			mav.addObject("userGroupList", page.getContent());	
		}
		
		
		return mav;
	}
	
	@SecuredEnum(UserPermission.USER_PERMISSION_LIST)
	@RequestMapping(value = "search-form", method = RequestMethod.GET)
	public ModelAndView searchForm(HttpServletRequest request) {
		breadCrumbService.addNode(MessageBundle.getMessageBundle("breadcrumb.usergroup.search"), 1, request);
		
		ModelAndView mav = new ModelAndView(Navigation.USER_PERMISSION_SEARCH.getPath());
		
		return mav;
	}

    private boolean entityHasErrors(UserGroup entity) {
		boolean hasErrors = false;
		
		if (entity != null) {
			if (validateName(entity)) {
				hasErrors = true;
			}
		}
		
		return hasErrors;
	}
	
    private boolean validateName(UserGroup entity){
    	boolean hasError = false;
    	
    	UserGroup result = userGroupService.findByName(entity.getName());
		
		if(result != null 
				&& !result.getId().equals(entity.getId())){
			hasError = true;
		}
		
		return hasError;
    }
    
    private String additionalValidation(UserGroup entity) {

src/main/webapp/WEB-INF/views/user-group/_authorship.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>

<s:message code="common.datePattern" var="datePattern" />

<jsp:useBean id="inputlength" class="br.apolo.common.util.InputLength"/>

<div class="form-group ">
	<label for="userGroup.createdBy.name" class="control-label">
		<s:message code="common.author" />
	</label>
	
	<form:input path="userGroup.createdBy.id" cssClass="input-block-level" cssStyle="display:none;" />
	
	<p>
		${userGroup.createdBy.name}
	</p>
</div>

<div class="form-group ">
	<label for="userGroup.creationDate" class="control-label">
		<s:message code="common.creationDate" />
	</label>
	
	<form:hidden path="userGroup.creationDate" cssClass="input-block-level" cssStyle="display:none;" />
	
	<p>
		<fmt:formatDate value="${userGroup.creationDate}" pattern="${datePattern}" />
	</p>
</div>

<c:if test="${userGroup.lastUpdatedBy.name != null}">
	<div class="form-group " <c:if test="${!readOnly}">style="display:none;"</c:if>>
		<label for="userGroup.lastUpdatedBy.name" class="control-label">
			<s:message code="common.lastUpdatedBy" />
		</label>
		
		<form:input path="userGroup.lastUpdatedBy.id" cssClass="input-block-level" cssStyle="display:none;" />
		
		<p>
			${userGroup.lastUpdatedBy.name}
		</p>
	</div>
</c:if>
	
<c:if test="${userGroup.lastUpdateDate != null}">
	<div class="form-group " <c:if test="${!readOnly}">style="display:none;"</c:if>>
		<label for="userGroup.lastUpdateDate" class="control-label">
			<s:message code="common.lastUpdateDate" />
		</label>
		
		<form:hidden path="userGroup.lastUpdateDate" cssClass="input-block-level" cssStyle="display:none;" />
		
		<p>
			<fmt:formatDate value="${userGroup.lastUpdateDate}" pattern="${datePattern}" />
		</p>
	</div>
</c:if>

src/main/webapp/WEB-INF/views/user-group/_permission-form.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>

<s:message code="common.datePattern" var="datePattern" />

<jsp:useBean id="inputlength" class="br.apolo.common.util.InputLength"/>

<input type="hidden" id="id" name="id" value="${userGroup.id}" />

<ul class="nav nav-tabs" id="formTab">
	<li class="active">
		<a href="#home">
			<span class="glyphicon glyphicon-tasks"></span>
		</a>
	</li>
	<c:if test="${readOnly}">
		<li>
			<a href="#authorShipTab">
				<span class="glyphicon glyphicon-user"></span>
			</a>
		</li>
	</c:if>
</ul>

<div class="tab-content">
	<div class="tab-pane active" id="home">

		<div class="form-group">
			<label for="name" class="control-label">
				<s:message code="user.group.name" />
			</label>
			<input class="form-control" type="text" id="name" name="name" value="${userGroup.name}" <c:if test="${readOnly}">readonly="true"</c:if> />
		</div>
		
		<c:choose>
			<c:when test="${not readOnly}">
				<div class="form-group">
					<label for="name" class="control-label">
						<s:message code="user.group.permissions.selected" />
					</label>
					<select name="permissions" id="listTo" size="5" multiple="multiple" class="input-block-level applyChosen form-control" <c:if test="${readOnly}">disabled="disabled"</c:if> data-placeholder='<s:message code="common.select" />'>
						<c:forEach items="${permissionList}" var="permission">
							<option value="${permission}"
								<c:forEach items="${userGroup.permissions}" var="groupPermission">
									<c:if test="${permission == groupPermission}">
										selected="selected"
									</c:if>
								</c:forEach>						
							><s:message code="user.permission.${permission}" /></option>
						</c:forEach>
					</select>
				</div>
			</c:when>
			<c:otherwise>
				<div class="form-group">
					<div class="panel panel-default">
						<div class="panel-heading">
							<strong>
								<s:message code="user.group.permissions.selected" />
							</strong>
						</div>
						<ul class="list-group">
							<c:forEach items="${userGroup.permissions}" var="permission">
								<li class="list-group-item">
									<s:message code="user.permission.${permission}" />
								</li>
							</c:forEach>
						</ul>
					</div>
				</div>
			</c:otherwise>
		</c:choose>
	</div>
	
	<div class="tab-pane" id="authorShipTab">
		<jsp:include page='_authorship.jsp'></jsp:include>
	</div>	
</div>
		

src/main/webapp/WEB-INF/views/user-group/_search-form.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags" %>

<form id="userForm" class="form-search form-inline" role="form" action="<s:url value="/user-group/search"></s:url>" method="post">
	<div class="form-group">
		<div class="input-group">
			<input type="text" id="searchParameter" name="searchParameter" value="${searchParameter}" class="search-query form-control" placeholder='<s:message code="user.group.search.field" />'>
			<span class="input-group-btn">
				<button type="submit" class="btn btn-info">
					<i class="glyphicon glyphicon-search"></i>
					<s:message code="common.search" /> 
				</button>
			</span>
		</div>
	</div>
</form>

src/main/webapp/WEB-INF/views/user-group/edit.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags" %>

<div class="panel panel-primary">
	<div class="panel-heading">
		<strong>
			<s:message code="user.group.edit.title" />
		</strong>
	</div>
	<div class="panel-body">
		<form id="userGroupForm" action="<s:url value="/user-group/save"></s:url>" method="post" role="form">
			<jsp:include page='_permission-form.jsp'></jsp:include>
			
			<div class="form-actions">
				<button type="submit" class="btn btn-primary">
					<i class="glyphicon glyphicon-ok"></i>
					<s:message code="common.save" /> 
				</button>
	
				<c:choose>
					<c:when test="${userGroup.id != null}">
						<a href='<s:url value="/user-group/view"></s:url>/${userGroup.id}' class="btn btn-default">
							<i class="glyphicon glyphicon-remove-circle"></i>
							<s:message code="common.cancel" />
						</a>				
					</c:when>
					<c:otherwise>
						<a href='<s:url value="/user-group/list"></s:url>' class="btn btn-default">
							<i class="glyphicon glyphicon-remove-circle"></i>
							<s:message code="common.cancel" />
						</a>
					</c:otherwise>
				</c:choose>
			</div>
		</form>
	</div>
</div>

src/main/webapp/WEB-INF/views/user-group/list.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags" %>

<jsp:include page='_search-form.jsp'></jsp:include>

<br />

<div class="panel panel-primary">
	<div class="panel-heading">
		<strong>
			<s:message code="user.group.list.title" />
		</strong>
	</div>
	<center>
		<jsp:include page='../_pagination.jsp'></jsp:include>
	</center>
	<c:choose>
		<c:when test="${userGroupList != null && not empty userGroupList}">
			<div class="table-responsive">
				<table class="table table-striped table-hover table-bordered">
					<thead>
						<tr>
							<th>
								<s:message code="user.group.name" />
							</th>
							<th>
								<s:message code="user.group.permissions" />
							</th>
							<security:authorize  ifAnyGranted="ROLE_ADMIN, ROLE_USER_PERMISSION_VIEW, ROLE_USER_PERMISSION_EDIT, ROLE_USER_PERMISSION_REMOVE">
								<th>
									<s:message code="common.actions" />
								</th>
							</security:authorize>
						</tr>
					</thead>
					
					<tbody>
						<c:forEach items="${userGroupList}" var="group">
							<tr id="userGroup_${group.id}">
								<td>
									<security:authorize  ifAnyGranted="ROLE_ADMIN, ROLE_USER_PERMISSION_VIEW">
										<a href='<s:url value="/user-group/view"></s:url>/${group.id}' class="btn btn-link">
											${group.name}
										</a>
									</security:authorize>
									<security:authorize  ifNotGranted="ROLE_ADMIN, ROLE_USER_PERMISSION_VIEW">
										${group.name}
									</security:authorize>
								</td>
								<td>
									<ul class="list-group">
										<c:forEach items="${group.permissions}" var="permission">
											<li class="list-group-item">
												<s:message code="user.permission.${permission}" />
											</li>
										</c:forEach>
									</ul>
								</td>
								<security:authorize  ifAnyGranted="ROLE_ADMIN, ROLE_USER_PERMISSION_VIEW, ROLE_USER_PERMISSION_EDIT, ROLE_USER_PERMISSION_REMOVE">
									<td>
										<div class="btn-group btn-group-sm">
											<security:authorize  ifAnyGranted="ROLE_ADMIN, ROLE_USER_PERMISSION_VIEW">
												<a href='<s:url value="/user-group/view"></s:url>/${group.id}' class="btn btn-small btn-default" data-toggle="tooltip" title="<s:message code="common.show" />">
													<i class="glyphicon glyphicon-zoom-in"></i>
												</a>
											</security:authorize>
											<security:authorize  ifAnyGranted="ROLE_ADMIN, ROLE_USER_PERMISSION_EDIT">
												<a href='<s:url value="/user-group/edit"></s:url>/${group.id}' class="btn btn-small btn-default" data-toggle="tooltip" title="<s:message code="common.edit" />">
													<i class="glyphicon glyphicon-edit"></i>
												</a>
											</security:authorize>
											<security:authorize  ifAnyGranted="ROLE_ADMIN, ROLE_USER_PERMISSION_REMOVE">
												<a href='#' class="btn btn-small btn-default" onclick="removeConfirmationDialogOpen('<s:url value="/user-group/remove"></s:url>/${group.id}', 'userGroup_${group.id}');" data-toggle="tooltip" title="<s:message code="common.remove" />">
													<i class="glyphicon glyphicon-remove"></i>
												</a>
											</security:authorize>
										</div>
									</td>
								</security:authorize>
							</tr>
						</c:forEach>
					</tbody>
				</table>
			</div>
		</c:when>
		<c:otherwise>
			<div class="panel-body">
				<p>
					<s:message code="common.nodatafound" htmlEscape="false"/>
				</p>
			</div>
		</c:otherwise>
	</c:choose>
	<center>
		<jsp:include page='../_pagination.jsp'></jsp:include>
	</center>
</div>

src/main/webapp/WEB-INF/views/user-group/new.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags" %>

<div class="panel panel-primary">
	<div class="panel-heading">
		<strong>
			<s:message code="user.group.new.title" />
		</strong>
	</div>
	<div class="panel-body">
		<form id="userGroupForm" action="<s:url value="/user-group/save"></s:url>" method="post" role="form">
			<jsp:include page='_permission-form.jsp'></jsp:include>
			
			<div class="form-actions">
				<button type="submit" class="btn btn-primary">
					<i class="glyphicon glyphicon-ok"></i>
					<s:message code="common.save" /> 
				</button>
	
				<c:choose>
					<c:when test="${userGroup.id != null}">
						<a href='<s:url value="/user-group/view"></s:url>/${userGroup.id}' class="btn btn-default">
							<i class="glyphicon glyphicon-remove-circle"></i>
							<s:message code="common.cancel" />
						</a>				
					</c:when>
					<c:otherwise>
						<a href='#' class="btn back btn-default" > 
							<i class="glyphicon glyphicon-remove-circle"></i>
							<s:message code="common.cancel" />
						</a>
					</c:otherwise>
				</c:choose>
			</div>
		</form>
	</div>
</div>