src/main/java/br/apolo/web/model/BreadCrumbTree.java
package br.apolo.web.model;

import java.util.ArrayList;
import java.util.List;

public class BreadCrumbTree {
	 
    private List<BreadCrumbNode> breadCrumb;
 
    private BreadCrumbNode findNode(BreadCrumbNode node) {
        for (BreadCrumbNode n : breadCrumb) {
            if (n.getLevel() == node.getLevel()) {
                return n;
            }
        }
        return null;
    }
 
    /**
     * Constructor
     */
    public BreadCrumbTree() {
        breadCrumb = new ArrayList<BreadCrumbNode>();
    }
 
    /**
     * Add node in the breadcrumb
     * @param node
     */
    public void addNode(BreadCrumbNode node) {
    	BreadCrumbNode c = findNode(node);
        if (c != null) {
            int position = breadCrumb.indexOf(c);
            for (int i = breadCrumb.size() - 1; i >= position; i--) {
                breadCrumb.remove(i);
            }
        } else {
            if (breadCrumb.size() > 0) {
                breadCrumb.get(breadCrumb.size() - 1).setValue(node.getValue());
            }
        }
        breadCrumb.add(node);
 
        List<BreadCrumbNode> nodeToRemove = new ArrayList<BreadCrumbNode>();
        for (int i = 0; i < breadCrumb.size()-1; i++) {             
            if (breadCrumb.get(i).getLevel() >= breadCrumb.get(breadCrumb.size() - 1).getLevel()) {
                nodeToRemove.add(breadCrumb.get(i));
            }
        }
 
        for (BreadCrumbNode remove : nodeToRemove) {
            breadCrumb.remove(remove);
        }
    }
 
    /**
     * Return the entire breadcrumb
     * @return
     */
    public List<BreadCrumbNode> getTree() {
        return breadCrumb;
    }
}

src/main/webapp/WEB-INF/views/include/breadcrumb.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

<ol id="breadcrumb" class="breadcrumb">
	<c:choose>
		<c:when test="${breadcrumb == null || breadcrumb.tree == null || empty breadcrumb.tree}">
			<li>
				<a id="first" href="<s:url value="/"></s:url>">
					<s:message code="breadcrumb.home" />
				</a>
			</li>
		</c:when>
		<c:otherwise>
			<c:forEach var="bc" items="${breadcrumb.tree}" varStatus="status">
				<c:choose>
					<c:when test="${status.index==0}">
						<li>
							<a id="first" href="<s:url value="/"></s:url>">
								<s:message code="breadcrumb.home" />
							</a>
						</li>
					</c:when>
					<c:when test="${status.index == fn:length(breadcrumb.tree)-1 && status.index!=0}">
						<li id="current" class="active">
							${bc.name}
						</li>
					</c:when>
					<c:otherwise>
						<li class="active">
							${bc.name}
						</li> 
					</c:otherwise>
				</c:choose>
			</c:forEach>
		</c:otherwise>
	</c:choose>
	<li class="pull-right onlyBigWindows">
		<s:message code="version" var="version"/>
		
		<button data-content="<s:message code="version"/>" 
				data-placement="left" 
				data-toggle="popover" 
				class="btn btn-link btn-xs applyPopoverHover" 
				href="#" 
				data-html="true">
			<s:message code="system.version" />:&nbsp; ${fn:substring(version, 0, 15)}
		</button>
	</li>
</ol>

src/main/webapp/WEB-INF/views/include/css.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

<link rel="icon" type="image/png" href='<c:url value="/resources/app/img/favicon.png" />'>

<link href='<c:url value="/resources/plugin/bootstrap/css/bootstrap.css" />' rel="stylesheet" media="screen"/>
<link href='<c:url value="/resources/plugin/bootstrap/css/bootstrap-theme.css" />' rel="stylesheet" />

<link href='<c:url value="/resources/plugin/jquery/themes/base/jquery-ui.css" />' rel="stylesheet" />

<link href='<c:url value="/resources/plugin/jquery-chosen/chosen.css" />' rel='stylesheet'>

<link href='<c:url value="/resources/plugin/tagit/css/jquery.tagit.css" />' rel='stylesheet'>
<link href='<c:url value="/resources/plugin/tagit/css/tagit.ui-zendesk.css" />' rel='stylesheet'>

<link href='<c:url value="/resources/plugin/cleditor/jquery.cleditor.css" />' rel='stylesheet'>

<link href='<c:url value="/resources/plugin/mediaelement/mediaelementplayer.min.css" />' rel='stylesheet'>

<link href='<c:url value="/resources/app/css/app.css" />' rel='stylesheet'>

src/main/webapp/WEB-INF/views/include/editDataDialog.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags"%>

<div id="editData" class="modal hide fade" tabindex="-1" data-role="dialog">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h4>
			<s:message code="common.edit" />
		</h4>
	</div>
	
	<div class="modal-body">
		<input type="text" id="dataInput" class="input-block-level"/>
		<input type="hidden" id="editingFieldName" />
	</div>
	
	<div class="modal-footer">
		<a href="#" class="btn" data-dismiss="modal">
			<i class="glyphicon glyphicon-remove-circle"></i>
			<s:message code="common.cancel" />
		</a>
		<a href="#" class="btn btn-primary" onclick="editData();">
			<i class="glyphicon glyphicon-check"></i>
			<s:message code="common.ok" />
		</a>
	</div>
</div>

src/main/webapp/WEB-INF/views/include/javascript.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

<script type="text/javascript">
	var App = function() {
		return {
			contextPath : '${pageContext.request.contextPath}',
			locale : '${sessionScope["org.springframework.web.servlet.i18n.SessionLocaleResolver.LOCALE"]}',
			readOnly : ${readOnly != null ? readOnly : false }
		};
	}();
</script>

<!-- jQuery -->
<script src='<c:url value="/resources/plugin/jquery/jquery-1.9.1.js" />'></script>

<script src='<c:url value="/resources/plugin/jquery/ui/jquery-ui.js" />'></script>

<script src='<c:url value="/resources/plugin/bootstrap/js/bootstrap.js" />'></script>

<!-- select or dropdown enhancer -->
<script src='<c:url value="/resources/plugin/jquery-chosen/chosen.jquery.js" />'></script>

<!-- tag-it script -->
<script src='<c:url value="/resources/plugin/tagit/js/tag-it.js" />'></script>

<!-- cleditor script -->
<script src='<c:url value="/resources/plugin/cleditor/jquery.cleditor.js" />'></script>

<!-- ellipsis script -->
<script src='<c:url value="/resources/plugin/jquery-ellipsis/jquery.ellipsis.js" />'></script>

<!-- mediaelement script -->
<script src='<c:url value="/resources/plugin/mediaelement/mediaelement-and-player.min.js" />'></script>

<!-- application scripts -->
<script type="text/javascript" src='<c:url value="/resources/app/js/app.js" />'></script>

src/main/webapp/WEB-INF/views/include/loadingDialog.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags"%>

<div class="container ">
	<div class="row ">
		<div id="loadingDialog" class="modal fade span1" tabindex="-1" data-role="dialog" style="text-align: center;">
			<div>
				<div>
					<img src='<c:url value="/resources/app/img/ajax-loader.gif" />' class="img-circle">
				</div>
			</div>
		</div>
	</div>
</div>

src/main/webapp/WEB-INF/views/include/message.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

<c:if test="${error || warn || msg}">
	<div class="row ">
		<div class="span12">
			<c:choose>
				<c:when test="${error}">
					<div class="alert alert-danger">
						${message}
					</div>		
				</c:when>
				<c:when test="${warn}">
					<div class="alert alert-warn">
						${message}
					</div>		
				</c:when>
				<c:when test="${msg}">
					<div class="alert alert-info">
						${message}
					</div>		
				</c:when>
			</c:choose>
		</div>
	</div>
</c:if>

src/main/webapp/WEB-INF/views/include/removeConfirmationDialog.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags"%>

<div id="removeConfirmationDialog" class="modal fade" tabindex="-1" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4>
					<s:message code="common.remove" />
				</h4>
			</div>
			
			<div class="modal-body">
				<p>
					<s:message code="common.remove.msg" htmlEscape="false"/>
				</p>
				<input type="hidden" id="removeConfirmationUrl" />
				<input type="hidden" id="removeConfirmationObjectId" />
			</div>
			
			<div class="modal-footer">
				<a href="#" class="btn btn-default" data-dismiss="modal">
					<i class="glyphicon glyphicon-remove-circle"></i>
					<s:message code="common.cancel" />
				</a>
				<a href="#" class="btn btn-danger" onclick="callRemove();">
					<i class="glyphicon glyphicon-remove"></i>
					<s:message code="common.remove" />
				</a>
			</div>
		</div>
	</div>
</div>

<div id="removeMsgDialog" class="modal fade" tabindex="-1" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4>
					<s:message code="common.remove" />
				</h4>
			</div>
			
			<div class="modal-body">
				<p id="removeMsg"></p>
			</div>
			
			<div class="modal-footer">
				<a href="#" class="btn btn-default" data-dismiss="modal">
					<i class="glyphicon glyphicon-check"></i>
					<s:message code="common.ok" />
				</a>
			</div>
		</div>
	</div>
</div>


<div id="removeRedirectionConfirmationDialog" class="modal hide fade" tabindex="-1" data-role="dialog">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h4>
			<s:message code="common.remove" />
		</h4>
	</div>
	
	<div class="modal-body">
		<p>
			<s:message code="common.remove.msg" htmlEscape="false"/>
		</p>
		<input type="hidden" id="removeRedirectionConfirmationUrl" />
		<input type="hidden" id="removeRedirectionConfirmationObjectId" />
	</div>
	
	<div class="modal-footer">
		<a href="#" class="btn" data-dismiss="modal">
			<s:message code="common.cancel" />
		</a>
		<a id="btnCallRemove" href="#" class="btn btn-danger">
			<s:message code="common.remove" />
		</a>
	</div>
</div>